# Generated by Django 3.1.1 on 2020-10-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercred',
            name='id',
        ),
        migrations.AddField(
            model_name='usercred',
            name='name',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='usercred',
            name='password',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='usercred',
            name='username',
            field=models.CharField(default=None, max_length=500, primary_key=True, serialize=False),
        ),
    ]
